import type { IvrFunctionDef } from "../domain/types.js";

export const GENERIC_FUNCTIONS: IvrFunctionDef[] = [
  {
    name: "answer",
    kind: "builtin",
    source: "generic",
    description: "Answer the ringing call",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "hangup",
    kind: "builtin",
    source: "generic",
    description: "Hang up immediately",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "repeat",
    kind: "builtin",
    source: "generic",
    description: "Play this step again",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "goto",
    kind: "builtin",
    source: "generic",
    description: "Go to another step (use Then if OK)",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "play",
    kind: "builtin",
    source: "generic",
    description: "Play an Asterisk sound, then follow Then if OK",
    pulseSlot: null,
    paramHint: "hello-world",
    enabled: true,
  },
  {
    name: "proc_createinteraction",
    kind: "pulse",
    source: "generic",
    description: "Create PULSE interaction (first IVR block; fail → hangup)",
    pulseSlot: "createInteraction",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_createsession",
    kind: "pulse",
    source: "generic",
    description: "Create PULSE session (IVR block after Create Interaction; fail → hangup)",
    pulseSlot: "createSession",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_addcallinteraction",
    kind: "pulse",
    source: "generic",
    description: "Add Call Interaction (language / menu / virtual queue / action)",
    pulseSlot: "addCallInteraction",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_setlanguagequeueid",
    kind: "pulse",
    source: "generic",
    description:
      "Send an explicit Pulse languageQueueId (old mw: 1=Urdu, 2=English). Prefer proc_setlanguage ur|en so IIM files and Pulse stay in sync.",
    pulseSlot: "addCallInteraction",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_setmenuqueueid",
    kind: "pulse",
    source: "generic",
    description: "Set menu queue id on PULSE (Call Interaction Add)",
    pulseSlot: "addCallInteraction",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_setvirtualqueueid",
    kind: "pulse",
    source: "generic",
    description: "Set virtual queue id on PULSE (Call Interaction Add)",
    pulseSlot: "addCallInteraction",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_reportproduct",
    kind: "pulse",
    source: "generic",
    description: "Send IVR selection / product to PULSE (Call Interaction Add)",
    pulseSlot: "addCallInteraction",
    paramHint: "",
    enabled: true,
  },
  {
    name: "setlanguage",
    kind: "pulse",
    source: "generic",
    description:
      "Set IIM file language (ur/en/sn/ps/ar/ot5–ot9) and send Pulse languageQueueId from IIM Setup (ur→1, en→2 by default).",
    pulseSlot: "addCallInteraction",
    paramHint: "ur",
    enabled: true,
  },
  {
    name: "proc_setlanguage",
    kind: "pulse",
    source: "generic",
    description:
      "Same as setlanguage: param is the IIM code (ur). Pulse gets the mapped languageQueueId from IIM Setup.",
    pulseSlot: "addCallInteraction",
    paramHint: "ur",
    enabled: true,
  },
  {
    name: "proc_enqueuecallrequest",
    kind: "pulse",
    source: "generic",
    description: "Request agent queue (Enqueue Call Request)",
    pulseSlot: "enqueueCallRequest",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_enqueuecall",
    kind: "pulse",
    source: "generic",
    description: "Poll queue position (Enqueue Call)",
    pulseSlot: "enqueueCall",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_startcallqueuetime",
    kind: "pulse",
    source: "generic",
    description: "Start call queue time on PULSE",
    pulseSlot: "startCallQueueTime",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_createcallback",
    kind: "pulse",
    source: "generic",
    description: "Create callback contact from IVR",
    pulseSlot: "createCallbackFromIvr",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_callfeedback",
    kind: "pulse",
    source: "generic",
    description: "Submit CSAT / post-call survey to PULSE (same interaction and session)",
    pulseSlot: "callFeedback",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_closesession",
    kind: "pulse",
    source: "generic",
    description: "Close PULSE session on hangup",
    pulseSlot: "closeSession",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_addcallrecordingpath",
    kind: "pulse",
    source: "generic",
    description: "Attach recording path to the PULSE interaction",
    pulseSlot: "addCallRecordingPath",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_transferfail",
    kind: "pulse",
    source: "generic",
    description: "Report transfer failed to PULSE",
    pulseSlot: "transferFail",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_agenticclosesession",
    kind: "pulse",
    source: "generic",
    description: "Close AI session before human enqueue",
    pulseSlot: "agenticCloseSession",
    paramHint: "",
    enabled: true,
  },
];

export function genericByName(name: string): IvrFunctionDef | undefined {
  const n = name.trim().toLowerCase();
  return GENERIC_FUNCTIONS.find((f) => f.name.toLowerCase() === n);
}
