import type { IvrFunctionDef } from "../domain/types.js";

export const GENERIC_FUNCTIONS: IvrFunctionDef[] = [
  {
    name: "answer",
    kind: "builtin",
    source: "generic",
    description: "Answer the ringing call",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "hangup",
    kind: "builtin",
    source: "generic",
    description: "Hang up immediately",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "repeat",
    kind: "builtin",
    source: "generic",
    description: "Play this step again",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "goto",
    kind: "builtin",
    source: "generic",
    description: "Go to another step (use Then if OK)",
    pulseSlot: null,
    paramHint: "",
    enabled: true,
  },
  {
    name: "play",
    kind: "builtin",
    source: "generic",
    description: "Play an Asterisk sound, then follow Then if OK",
    pulseSlot: null,
    paramHint: "hello-world",
    enabled: true,
  },
  {
    name: "proc_createinteraction",
    kind: "pulse",
    source: "generic",
    description: "Create PULSE interaction (before answer)",
    pulseSlot: "preAnswer",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_createsession",
    kind: "pulse",
    source: "generic",
    description: "Create PULSE session",
    pulseSlot: "startSession",
    paramHint: "",
    enabled: true,
  },
  {
    name: "proc_setlanguagequeueid",
    kind: "pulse",
    source: "generic",
    description: "Set language queue id on PULSE",
    pulseSlot: "ivrStep",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_setmenuqueueid",
    kind: "pulse",
    source: "generic",
    description: "Set menu queue id on PULSE",
    pulseSlot: "ivrStep",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_setvirtualqueueid",
    kind: "pulse",
    source: "generic",
    description: "Set virtual queue id on PULSE",
    pulseSlot: "ivrStep",
    paramHint: "1",
    enabled: true,
  },
  {
    name: "proc_reportproduct",
    kind: "pulse",
    source: "generic",
    description: "Send IVR selection / product to PULSE",
    pulseSlot: "ivrStep",
    paramHint: "",
    enabled: true,
  },
  {
    name: "setlanguage",
    kind: "pulse",
    source: "generic",
    description: "Set caller language on PULSE",
    pulseSlot: "ivrStep",
    paramHint: "0",
    enabled: true,
  },
];

export function genericByName(name: string): IvrFunctionDef | undefined {
  const n = name.trim().toLowerCase();
  return GENERIC_FUNCTIONS.find((f) => f.name.toLowerCase() === n);
}
