/** Placeholder IIM slots to drop. These were not Pulse endpoints. */
export const LEGACY_PULSE_SLOTS = [
  "preAnswer",
  "startSession",
  "enqueue",
  "agentConnect",
  "hold",
  "transfer",
  "hangup",
  "ivrStep",
  "aicb",
] as const;

export const LEGACY_SLOT_REMAP: Record<string, string> = {
  preAnswer: "createInteraction",
  startSession: "createSession",
  ivrStep: "addCallInteraction",
  enqueue: "enqueueCallRequest",
  hangup: "closeSession",
};

export type PulseApiSeed = {
  slot: string;
  name: string;
  description: string;
  /** Pulse path only, for the description. The stored URL is per API and must be a full http(s) URL. */
  path: string;
  mock: unknown;
};

const INTERACTION_ID = "4da0ed64-bb28-4ab6-a44e-e5adcc0f320f";
const SESSION_ID = "d7003eb0-5af8-4336-ab78-eb0d40d69f2c";
const AGENT_ID = "00000000-0000-0000-0000-000000000000";
const CNIC = "4220117236256";
const CLI = "03001234567";

const ok = { item1: true, item2: "Success" };
const profile = {
  customerShortName: "AHMED",
  customerName: "AHMED ALI KHAN",
  fatherName: "ALI KHAN",
  cnic: CNIC,
  mobileNumber: CLI,
  dateofBirth: "6/6/1985",
  nationality: "Pakistani",
  gender: "Male",
  emailAddress: "",
  isPriority: false,
  isHighAlert: false,
  customerPriorityStatus: "NORMAL",
  accountNumber: "1234567890",
  accountStatus: "ACTIVE",
  userId: "pulse-mock-user",
  hasTpin: true,
  isTpinGenerated: true,
};

/**
 * Unique Pulse HTTP APIs from the old middleware client, with dummy-shaped mocks.
 * Each IIM row has its own full URL (different Pulse servers are allowed). There is no shared base URL.
 */
export const PULSE_API_SEEDS: PulseApiSeed[] = [
  {
    slot: "createInteraction",
    name: "CX / Create Interaction",
    description: "POST /api/Ivr/CreateInteraction — IIM calls this before answer or reject (cli, autoAgentId, direction, refCallId, designatedNumber).",
    path: "/api/Ivr/CreateInteraction",
    mock: {
      interactionId: INTERACTION_ID,
      cli: CLI,
      isCliAlreadyExist: false,
      refCallId: "channel-mock",
      ivrRouting: 2,
    },
  },
  {
    slot: "createSession",
    name: "CX / Create Session",
    description: "POST /api/Ivr/CreateSession — IIM calls this before answer or reject. Returns sessionId.",
    path: "/api/Ivr/CreateSession",
    mock: {
      sessionId: SESSION_ID,
      interactionId: INTERACTION_ID,
      callReferenceId: "channel-mock",
      channelId: 1,
      callStatus: "start",
      cli: CLI,
      recordingRelativePath: "",
      sessionStartDateTime: "2026-01-01T00:00:00.000Z",
      sessionEndDateTime: "2026-01-01T00:00:00.000Z",
      isPriority: false,
      isHighAlert: false,
    },
  },
  {
    slot: "addCallInteraction",
    name: "CX / Call Interaction Add",
    description: "POST /api/CallInteraction/Add — language, menu, virtual queue, and action breadcrumb from the live call.",
    path: "/api/CallInteraction/Add",
    mock: {
      id: "96d6ec76-c12b-4adf-9148-c19b9942a95f",
      interactionId: INTERACTION_ID,
      sessionId: SESSION_ID,
      callReferenceId: "channel-mock",
      languageQueueId: 1,
      menuQueueId: 1,
      virtualQueueId: 0,
      action: "LanguageSelected",
      isActive: true,
      createdBy: 1,
      createdOn: "2026-01-01T00:00:00.000Z",
    },
  },
  {
    slot: "enqueueCallRequest",
    name: "Queue / Enqueue Call Request",
    description: "POST /api/Ivr/Call/EnqueueCallRequest — ask Pulse to queue for an agent.",
    path: "/api/Ivr/Call/EnqueueCallRequest",
    mock: { action: "EnqueueCall", agentId: AGENT_ID },
  },
  {
    slot: "enqueueCall",
    name: "Queue / Enqueue Call (position)",
    description: "POST /api/Ivr/EnqueueCall — poll queue position, wait, max wait, callback window.",
    path: "/api/Ivr/EnqueueCall",
    mock: {
      interactionId: INTERACTION_ID,
      sessionId: SESSION_ID,
      queuePosition: 10,
      queueWaitTime: 300,
      maxQueueWaitTime: 600,
      callBackTime: 20,
    },
  },
  {
    slot: "startCallQueueTime",
    name: "Queue / Start Call Queue Time",
    description: "POST /api/Ivr/StartCallQueueTime — queue clock started.",
    path: "/api/Ivr/StartCallQueueTime",
    mock: {},
  },
  {
    slot: "createCallbackFromIvr",
    name: "Queue / Create Callback From IVR",
    description: "POST /api/Ivr/CreateCallbackContactFromIVR — off-hours or max wait callback.",
    path: "/api/Ivr/CreateCallbackContactFromIVR",
    mock: {},
  },
  {
    slot: "callFeedback",
    name: "CX / Call Feedback",
    description: "POST /api/Ivr/CallFeedback — CSAT after the agent hangs up (same interaction/session, no new create).",
    path: "/api/Ivr/CallFeedback",
    mock: {},
  },
  {
    slot: "closeSession",
    name: "CX / Close Session",
    description: "POST /api/Ivr/CloseSession — IIM retries this on hangup/drop whenever interaction and session exist.",
    path: "/api/Ivr/CloseSession",
    mock: {},
  },
  {
    slot: "addCallRecordingPath",
    name: "CX / Add Call Recording Path",
    description: "POST /api/Ivr/AddCallRecordingPath — attach recording to the interaction.",
    path: "/api/Ivr/AddCallRecordingPath",
    mock: {},
  },
  {
    slot: "transferFail",
    name: "CX / Transfer Failed",
    description: "POST /api/Ivr/Call/TransferedFail — agent transfer failed.",
    path: "/api/Ivr/Call/TransferedFail",
    mock: {},
  },
  {
    slot: "agenticCloseSession",
    name: "CX / Agentic Close Session",
    description: "POST /api/Ivr/AgenticCloseSession — AI session closed before human enqueue.",
    path: "/api/Ivr/AgenticCloseSession",
    mock: {
      sessionId: "cee9af9e-a80a-4d1f-b6e1-d145380d6844",
      interactionId: INTERACTION_ID,
      callReferenceId: "channel-mock",
      channelId: 1,
      callStatus: "Human Agent Session Started",
      sessionStartDateTime: "2026-01-01T00:00:00.000Z",
      sessionEndDateTime: "2026-01-01T00:00:00.000Z",
      isPriority: false,
      isHighAlert: false,
    },
  },
  {
    slot: "complaintStatus",
    name: "CX / Complaint Status",
    description: "POST /api/Ivr/Complaints/Status — look up a complaint by CNIC / number.",
    path: "/api/Ivr/Complaints/Status",
    mock: { complaintStatus: 2, cnic: CNIC, complaintNumber: "CMP-1001" },
  },
  {
    slot: "customerProfileBusiness",
    name: "Profile / Customer Profile (Business API)",
    description: "POST /api/BusinessApi/CustomerProfile — JS Bank and default profile search.",
    path: "/api/BusinessApi/CustomerProfile",
    mock: [profile],
  },
  {
    slot: "customerProfileIvrSelfServe",
    name: "Profile / Customer Profile (IVR Self-Serve)",
    description: "POST /api/IvrSelfServe/CustomerProfile — AI / Bank Islami profile search.",
    path: "/api/IvrSelfServe/CustomerProfile",
    mock: [profile],
  },
  {
    slot: "customerProfileForIvr",
    name: "Hugo / Customer Profile For IVR",
    description: "POST /api/BusinessApi/CustomerProfileForIvr — Hugo find customer by CNIC.",
    path: "/api/BusinessApi/CustomerProfileForIvr",
    mock: {
      success: "true",
      customerName: "AHMED ALI KHAN",
      customerShortName: "AHMED",
      cnic: CNIC,
      mobileNumber: CLI,
      accountNumber: "1234567890",
      userId: "hugo-dummy-user",
      hasTpin: true,
      isTpinGenerated: true,
      accountStatus: "ACTIVE",
      accountType: "Individual",
      branch: "Karachi Main",
    },
  },
  {
    slot: "createTelPin",
    name: "PIN / Create Tel PIN",
    description: "POST /api/CustomerPINValidation/pin/createTelPin — create TPIN (Hugo / Sindh / JS).",
    path: "/api/CustomerPINValidation/pin/createTelPin",
    mock: { success: true, item1: true, item2: "TPIN created successfully", cnic: CNIC },
  },
  {
    slot: "createTelPinLegacy",
    name: "PIN / Create Tel PIN (legacy)",
    description: "POST /api/CustomerPINValidation/createTelPin — older create-TPIN path.",
    path: "/api/CustomerPINValidation/createTelPin",
    mock: {},
  },
  {
    slot: "validateTelPin",
    name: "PIN / Validate Tel PIN",
    description: "POST /api/CustomerPINValidation/pin/isValidTelPin — check TPIN (test PIN 2345 in old dummy).",
    path: "/api/CustomerPINValidation/pin/isValidTelPin",
    mock: {
      success: true,
      item1: true,
      item2: "TPIN validated successfully",
      isValidTelPin: true,
      cnic: CNIC,
    },
  },
  {
    slot: "validateTelPinLegacy",
    name: "PIN / Validate Tel PIN (legacy)",
    description: "POST /api/CustomerPINValidation/isValidTelPin — older validate-TPIN path.",
    path: "/api/CustomerPINValidation/isValidTelPin",
    mock: {},
  },
  {
    slot: "ivrCreateTpin",
    name: "PIN / Create TPIN (Self-Serve)",
    description: "POST /api/IvrSelfServe/CreateTpin",
    path: "/api/IvrSelfServe/CreateTpin",
    mock: ok,
  },
  {
    slot: "ivrTpinGeneration",
    name: "PIN / TPIN Generation (Self-Serve)",
    description: "POST /api/IvrSelfServe/TpinGeneration",
    path: "/api/IvrSelfServe/TpinGeneration",
    mock: ok,
  },
  {
    slot: "ivrTpinChange",
    name: "PIN / TPIN Change (Self-Serve)",
    description: "POST /api/IvrSelfServe/TpinChange",
    path: "/api/IvrSelfServe/TpinChange",
    mock: { item1: true, item2: "TPIN changed successfully" },
  },
  {
    slot: "ivrIsValidTelPin",
    name: "PIN / Is Valid Tel PIN (Self-Serve)",
    description: "POST /api/IvrSelfServe/isValidTelPin",
    path: "/api/IvrSelfServe/isValidTelPin",
    mock: {
      item1: true,
      item2: "successfully verified Tpin",
      responseBody: { item1: true, item2: "successfully verified Tpin" },
    },
  },
  {
    slot: "createAtmPin",
    name: "PIN / Create ATM PIN",
    description: "POST /api/IvrSelfServe/CreateATMPin",
    path: "/api/IvrSelfServe/CreateATMPin",
    mock: { item1: true, item2: "Success", responseBody: { item1: true, item2: "Success" } },
  },
  {
    slot: "changeAtmPin",
    name: "PIN / Change ATM PIN",
    description: "POST /api/IvrSelfServe/ChangeATMPin",
    path: "/api/IvrSelfServe/ChangeATMPin",
    mock: { item1: true, item2: "Success", responseBody: { item1: true, item2: "Success" } },
  },
  {
    slot: "validateAtmPin",
    name: "PIN / Validate ATM PIN",
    description: "POST /api/IvrSelfServe/ValidateATMPin",
    path: "/api/IvrSelfServe/ValidateATMPin",
    mock: { item1: true, item2: "Success", responseBody: { item1: true, item2: "Success" } },
  },
  {
    slot: "createCreditCardAtmPin",
    name: "PIN / Create Credit Card ATM PIN",
    description: "POST /api/IvrSelfServe/CreateCreditCardATMPin",
    path: "/api/IvrSelfServe/CreateCreditCardATMPin",
    mock: { item1: true, item2: "Success" },
  },
  {
    slot: "sendCreateAtmPinEuroNet",
    name: "PIN / Create ATM PIN (EuroNet Debit)",
    description: "POST /api/BusinessApi/SendCreateATMPINRequestsForEuroNetDebit",
    path: "/api/BusinessApi/SendCreateATMPINRequestsForEuroNetDebit",
    mock: ok,
  },
  {
    slot: "businessCreateAtmPin",
    name: "PIN / Create ATM PIN (Business API)",
    description: "POST /api/BusinessApi/CreateATMPin — debit card PIN generation.",
    path: "/api/BusinessApi/CreateATMPin",
    mock: { item1: true, item2: "ATM PIN generated successfully" },
  },
  {
    slot: "customerAccountCards",
    name: "Card / Customer Account Cards",
    description: "POST /api/IvrSelfServe/CustomerAccountCards",
    path: "/api/IvrSelfServe/CustomerAccountCards",
    mock: {
      cards: [
        { cardNumber: "4567890012341111", maskedCardNumber: "************1111" },
        { cardNumber: "4567890012342222", maskedCardNumber: "************2222" },
      ],
    },
  },
  {
    slot: "customerAccountCardsForIvr",
    name: "Hugo / Customer Account Cards For IVR",
    description: "POST /api/BusinessApi/CustomerAccountCardsForIvr",
    path: "/api/BusinessApi/CustomerAccountCardsForIvr",
    mock: {
      cards: [{ cardNumber: "4567890012341111", maskedCardNumber: "************1111" }],
    },
  },
  {
    slot: "cardBlocking",
    name: "Card / Card Blocking",
    description: "POST /api/IvrSelfServe/CardBlocking",
    path: "/api/IvrSelfServe/CardBlocking",
    mock: { item1: true, item2: "Card blocked successfully" },
  },
  {
    slot: "cardBlockingForIvr",
    name: "Hugo / Card Blocking For IVR",
    description: "POST /api/BusinessApi/CardBlockingForIvr",
    path: "/api/BusinessApi/CardBlockingForIvr",
    mock: { item1: true, item2: "Card blocked successfully" },
  },
  {
    slot: "cardActivation",
    name: "Card / Card Activation",
    description: "POST /api/IvrSelfServe/CardActivation",
    path: "/api/IvrSelfServe/CardActivation",
    mock: { item1: true, item2: "Card activated successfully" },
  },
  {
    slot: "getCustomerAccountsByCnic",
    name: "Account / Get Customer Accounts By CNIC",
    description: "POST /api/IvrSelfServe/GetCustomerAccountsByCnic",
    path: "/api/IvrSelfServe/GetCustomerAccountsByCnic",
    mock: {
      accounts: [
        {
          accountNumber: "00101234567890",
          branchCode: "PK0010001",
          mobileNumber: CLI,
          accountStatus: "Active",
          balance: "15320.50",
        },
        {
          accountNumber: "00109876543210",
          branchCode: "PK0010002",
          mobileNumber: "03007654321",
          accountStatus: "Active",
          balance: "2450.00",
        },
      ],
    },
  },
  {
    slot: "balanceInquiry",
    name: "Account / Balance Inquiry",
    description: "POST /api/IvrSelfServe/BalanceInquiry",
    path: "/api/IvrSelfServe/BalanceInquiry",
    mock: { accountNumber: "00101234567890", balance: "15320.50" },
  },
  {
    slot: "getCustomerTransactions",
    name: "Account / Get Customer Transactions",
    description: "POST /api/IvrSelfServe/GetCustomerTransactions",
    path: "/api/IvrSelfServe/GetCustomerTransactions",
    mock: {
      accountNumber: "00101234567890",
      transactions: [
        { amount: "500.00", type: "debit" },
        { amount: "1500.00", type: "credit" },
      ],
    },
  },
  {
    slot: "singleClickBlockSelfServe",
    name: "Channel / Single Click Block (Self-Serve)",
    description: "POST /api/IvrSelfServe/SingleClickBlockInstrumentList",
    path: "/api/IvrSelfServe/SingleClickBlockInstrumentList",
    mock: { item1: true, item2: "succefully blocked all services" },
  },
  {
    slot: "singleClickBlockBusiness",
    name: "Channel / Single Click Block (Business API)",
    description: "POST /api/BusinessApi/SingleClickBlockInstrumentList",
    path: "/api/BusinessApi/SingleClickBlockInstrumentList",
    mock: { item1: true, item2: "succefully blocked all services" },
  },
  {
    slot: "deActivateCustomerDigitalApp",
    name: "Channel / Deactivate Customer Digital App",
    description: "POST /api/IvrSelfServe/DeActivateCustomerDigitalApp",
    path: "/api/IvrSelfServe/DeActivateCustomerDigitalApp",
    mock: { item1: true, item2: "Mobile app blocked successfully" },
  },
  {
    slot: "getMobileStatus",
    name: "Channel / Get Mobile Status",
    description: "POST /api/IvrSelfServe/GetMobileStatus",
    path: "/api/IvrSelfServe/GetMobileStatus",
    mock: { item1: true, item2: "Active", status: "A" },
  },
  {
    slot: "updateMobileStatus",
    name: "Channel / Update Mobile Status",
    description: "POST /api/IvrSelfServe/UpdateMobileStatus",
    path: "/api/IvrSelfServe/UpdateMobileStatus",
    mock: { item1: true, item2: "Active" },
  },
  {
    slot: "getSmsStatus",
    name: "Channel / Get SMS Status",
    description: "POST /api/IvrSelfServe/GetSMSStatus",
    path: "/api/IvrSelfServe/GetSMSStatus",
    mock: { item1: true, item2: "Active", status: "A" },
  },
  {
    slot: "updateSmsStatus",
    name: "Channel / Update SMS Status",
    description: "POST /api/IvrSelfServe/UpdateSMSStatus",
    path: "/api/IvrSelfServe/UpdateSMSStatus",
    mock: { item1: true, item2: "Active" },
  },
  {
    slot: "blockMobileChannelForIvr",
    name: "Hugo / Block Mobile Channel For IVR",
    description: "POST /api/BusinessApi/BlockMobileChannelForIvr",
    path: "/api/BusinessApi/BlockMobileChannelForIvr",
    mock: {
      success: true,
      status: "BLOCKED",
      serviceType: "DIGITAL_SERVICES",
      cnic: CNIC,
      message: "Digital services blocked successfully",
    },
  },
  {
    slot: "hugoReportFraud",
    name: "Hugo / Report Fraud",
    description: "POST /api/Hugo/ReportFraud",
    path: "/api/Hugo/ReportFraud",
    mock: { success: true, message: "Fraud reported" },
  },
  {
    slot: "hugoBlockAllServices",
    name: "Hugo / Block All Services",
    description: "POST /api/Hugo/BlockAllServices",
    path: "/api/Hugo/BlockAllServices",
    mock: { success: true, message: "All services blocked" },
  },
  {
    slot: "hugoCheckWorkingDay",
    name: "Hugo / Check Working Day",
    description: "POST /api/Hugo/CheckWorkingDay",
    path: "/api/Hugo/CheckWorkingDay",
    mock: { isWorkingDay: true },
  },
  {
    slot: "hugoCheckWorkingHours",
    name: "Hugo / Check Working Hours",
    description: "POST /api/Hugo/CheckWorkingHours",
    path: "/api/Hugo/CheckWorkingHours",
    mock: { isWorkingHours: true },
  },
  {
    slot: "aikCustomerProfile",
    name: "AIK / Customer Profile",
    description: "POST /api/Aik/CustomerProfile",
    path: "/api/Aik/CustomerProfile",
    mock: {
      isRegistered: true,
      customerID: "AIK-CUSTOMER-001",
      cnic: CNIC,
      mobileNo: CLI,
      customerName: "AIK Digital Test Customer",
    },
  },
  {
    slot: "aikVerifyAccount",
    name: "AIK / Verify Account",
    description: "POST /api/Aik/VerifyAccount",
    path: "/api/Aik/VerifyAccount",
    mock: { success: true, isVerified: true, customerID: "AIK-CUSTOMER-001", cnic: CNIC },
  },
  {
    slot: "aikBalanceInquiry",
    name: "AIK / Balance Inquiry",
    description: "POST /api/Aik/BalanceInquiry",
    path: "/api/Aik/BalanceInquiry",
    mock: { success: true, balance: "1250.75", customerID: "AIK-CUSTOMER-001", cnic: CNIC },
  },
  {
    slot: "anyJobForRoboCalls",
    name: "Robo / Any Job For Robo Calls",
    description: "POST /api/RoboCalls/AnyJobForRoboCalls",
    path: "/api/RoboCalls/AnyJobForRoboCalls",
    mock: null,
  },
  {
    slot: "anyJobStatusForRoboCalls",
    name: "Robo / Any Job Status For Robo Calls",
    description: "POST /api/RoboCalls/AnyJobStatusForRoboCalls",
    path: "/api/RoboCalls/AnyJobStatusForRoboCalls",
    mock: {},
  },
];
